### PR TITLE
all diagrams

### LINKED ISSUE #66: sequence diagrams for all flows

### PR DESCRIPTION
**Pull request by h1alexbel**
@l3r8yJ take a look please
closes #66 

---

## PR-Codex overview
This PR focuses on adding PlantUML diagrams for the register chat ID flow, add token success flow, token validation process, and notifications read flow. 

### Detailed summary
- Added `register-chat.puml` diagram for the register chat ID flow.
- Added `puml.yaml` workflow file for generating SVG diagrams.
- Added `add-token.puml` diagram for the add token success flow.
- Added `token-validation.puml` diagram for the token validation process.
- Added `notifications-read.puml` diagram for the notifications read flow.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@h1alexbel thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by zoeself** [comment]
@h1alexbel please review this Pull Request. Deadline (when it should be merged or closed) is ``2023-09-04T06:59:03.143679``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by h1alexbel** [comment]
@zoeself deregister

**Comment by h1alexbel** [comment]
@zoeself assign @l3r8yJ

**Comment by zoeself** [comment]
> @zoeself assign @l3r8yJ 

@h1alexbel didn't understand that, sorry.

**Comment by h1alexbel** [comment]
@l3r8yJ reminder

**Review by l3r8yJ — APPROVED** [review]

**Comment by l3r8yJ** [comment]
looks good to me! @rultor merge

**Comment by l3r8yJ** [comment]
@rultor merge

**Pull request merged**
