### PR TITLE
more clean diagrams

### PR DESCRIPTION
**Pull request by h1alexbel**
## PR-Codex overview
This PR focuses on adding a new communication channel between the hub and the bot. 

### Detailed summary
- Added a new participant `bot` in both `token-validation.puml` and `add-token.puml` diagrams.
- Added a new message flow between `hub` and `bot` indicating the status of a token alias for a specific chat ID.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by h1alexbel** [comment]
@l3r8yJ check this one

**Comment by zoeself** [comment]
@h1alexbel please review this Pull Request. Deadline (when it should be merged or closed) is ``2023-09-11T20:09:02.181344``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by h1alexbel** [comment]
@l3r8yJ ping

**Review by l3r8yJ — APPROVED** [review]

**Comment by l3r8yJ** [comment]
@rultor merge

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
