### PR TITLE
Pom plugins, checkstyle, 2 indentations

### LINKED ISSUE #5: Find a Spring-compatible checkstyle configuration
We need to find some existing configuration for checkstyle, because setting it up manually might piss off the person who tries to do it. Spring framework is not the best solution for clean code, but we should try to keep it as clean as possible

### PR DESCRIPTION
**Pull request by h1alexbel**
closes #5

### CODE REVIEW

**Comment by h1alexbel** [comment]
@l3r8yJ, take a look, please

**Comment by h1alexbel** [comment]
@l3r8yJ, please, take a look

**Comment by h1alexbel** [comment]
@l3r8yJ I will up the coverage

**Comment by h1alexbel** [comment]
@l3r8yJ ready to review

**Review by l3r8yJ — APPROVED** [review]
@h1alexbel lgtm

**Comment by l3r8yJ** [comment]
@rultor merge

**Comment by h1alexbel** [comment]
@l3r8yJ I gave ADMIN access to rultor, try again, please

**Comment by l3r8yJ** [comment]
@rultor merge

**Pull request merged**
