### PR TITLE
`TgBot` instead of `Bot`, double cp fixed, authors added

### LINKED ISSUE #31: Bot class naming
https://github.com/Blamer-io/bot/blob/afcf08ab19e300aeb1015e8fc6301f62e7b49c46/src/main/java/io/blamer/bot/bot/Bot.java#L52

@l3r8yJ It can be named `TgBot`. I believe it's a better naming for this class

WDYT?

### PR DESCRIPTION
**Pull request by h1alexbel**
closes #31

---

## PR-Codex overview
This PR refactors the Telegram bot implementation by renaming and reorganizing classes and packages, adding author and version information, and replacing the use of `generators` with `conversations`. 

### Detailed summary
- Renamed `Bot` to `TgBot` and moved it to `io.blamer.bot.agents.tg` package
- Renamed `BotInitializer` to `TgInitializer`
- Renamed `BotConfiguration` to `ExtTg`
- Renamed `BotTest` to `TgBotTest`
- Added author and version information to various files
- Replaced the use of `generators` with `conversations` in `TgBot`
- Moved `package-info.java` files to their parent packages
- Deleted `package-info.java` file in `io.blamer.bot.bot` package
- Updated `TgBotTest` to test the new changes

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Review by l3r8yJ — APPROVED** [review]
nice, lgtm

**Comment by l3r8yJ** [comment]
@rultor merge

**Comment by h1alexbel** [comment]
@l3r8yJ maybe we should remove `Bot` interface?

**Comment by h1alexbel** [comment]
or at least rename its method to `init()`

**Comment by h1alexbel** [comment]
@l3r8yJ WDYT?

**Comment by h1alexbel** [comment]
> @h1alexbel we can use `@PostConstruct` on interface method and say call it `loadCommands`/`init`/`initCommands`. I suggest to rename interface like to something like`BotInitialCommands`

@l3r8yJ I don't think that hiding `PostConstruct` will help to improve maintainability

**Comment by h1alexbel** [comment]
@l3r8yJ moreover we don't need to expose this method to others

**Comment by h1alexbel** [comment]
@l3r8yJ yes, it's exactly what I'm suggesting

**Comment by l3r8yJ** [comment]
@h1alexbel can i try to merge?

**Comment by h1alexbel** [comment]
@l3r8yJ I will up the coverage

**Comment by h1alexbel** [comment]
@l3r8yJ ready for review

**Review by l3r8yJ — APPROVED** [review]
lgtm

**Comment by l3r8yJ** [comment]
@rultor merge

**Comment by l3r8yJ** [comment]
> @l3r8yJ chat not found in test:
> 
> https://stackoverflow.com/a/41291666/19147117
> 
> maybe we need to create `fake` client and call it on `ITCase`

I think we can find a ready-made solution to test the telegram api. The fake telegram API looks like a separate open source product, it is too big. 

we can create a new idea issue, wdyt?

**Comment by l3r8yJ** [comment]
@h1alexbel thanks!

**Comment by h1alexbel** [comment]
@l3r8yJ did you mean creating issue into `blamer-io/ideas` or what?

**Comment by l3r8yJ** [comment]
@h1alexbel yes

**Comment by h1alexbel** [comment]
@l3r8yJ created. [here](https://github.com/Blamer-io/ideas/issues/1) it is

**Pull request merged**
